[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/gold-admin-mirror-7f3a/*"
  to = "/gold-admin-mirror-7f3a/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
